### ISSUE TITLE
Incorrect version in lean-toolchain

### ISSUE THREAD

**Issue by vasnesterov** [fgdorais/lean4-unicode-basic#3]
Hi! I am trying to run [LeanDojo](https://github.com/lean-dojo/LeanDojo) that apparently uses your repo, and it crashes because there is no tag `4.0.0` in https://github.com/leanprover/lean4, but `v4.0.0`. Maybe it should be prefixed with `v` in your lean-toolchain either?

**Comment by fgdorais** [comment]
Thanks for the report! It's fixed now.
